[build]
builder = "NIXPACKS"

[build.nixpacks]
providers = ["python"]

[build.nixpacks.env]
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"
